version: '3.9'

services:
  tests:
    build: .
    command: pytest tests.py
  web:
    build: .
    command: python3 main.py
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - tests